name: user_cent_med_app

description: MVP for User-Centered Medical Equipment Management App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  cloud_functions: ^6.0.2
  flutter_riverpod: ^3.0.0
  cached_network_image: ^3.4.1
  file_picker: ^10.3.2
  flutter_local_notifications: ^19.4.2
  http: ^1.5.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  timezone: ^0.10.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.3.2
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  video_player: ^2.9.2
  wakelock_plus: ^1.2.6
  video_thumbnail: ^0.5.3
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6 # universal video libs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
